<a href="https://colab.research.google.com/github/VinuthaKSJBIT/EDA/blob/main/Chap1_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  # Python , NumPy and Pandas
* **Python** is the "boss" that tells the computer what to do using simple, English-like words. It is great for logic, but it isn't naturally built to handle millions of numbers at lightning speed.
* **NumPy** stands for **Numerical Python**. It introduces the Array, which is a way to store data that the computer can process much faster than a standard Python list.
* **Pandas** is built on top of NumPy. While NumPy is great for raw numbers, it’s not very good at handling **"labeled" data** (like a spreadsheet with names, dates, and prices).
* **Pandas** is like Excel on steroids. It gives your data "headers" and "indexes" so you can say "Show me all sales from January" instead of "Show me row 5,422."

Let's use a real-world scenario. Imagine you are running a Lemonade Stand.

Here is how our three "workers" handle the business:

# 1. Python: The Logic (The Owner)
Python is the person who makes the rules. It handles things like "If it's raining, don't open the stand" or "Say 'Hello' to every customer."

In [1]:
# Standard Python: A simple list of sales
daily_sales = [10, 12, 15, 8, 20]

# Python logic: If sales are low, print a warning
for sale in daily_sales:
    if sale < 10:
        print("Slow day!")

Slow day!

# 2. NumPy: The Calculator (The Accountant)
NumPy doesn't care about "Hello" or "Rain." It only cares about math. If you give it 1,000 days of sales data, it can calculate the total or the average in a fraction of a second.

In [2]:
import numpy as np

# Convert our list to a NumPy Array
sales_array = np.array([10, 12, 15, 8, 20])

# Do math to the WHOLE group at once
# Let's say each lemonade costs $2. Calculate revenue for every day:
revenue = sales_array * 2

print(revenue) # Output: [20, 24, 30, 16, 40]

[20 24 30 16 40]

# 3. Pandas: The Spreadsheet (The Manager)
Pandas takes those raw numbers from NumPy and gives them labels. It’s like moving from a scrap of paper to a professional Excel file. It knows which number belongs to "Monday" and which belongs to "Friday."

In [3]:
import pandas as pd

# Create a "DataFrame" (The Spreadsheet)
data = {
    'Day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Cups_Sold': [10, 12, 15, 8, 20],
    'Weather': ['Sunny', 'Sunny', 'Cloudy', 'Rainy', 'Sunny']
}

df = pd.DataFrame(data)

# Now you can ask "Manager" questions:
sunny_days = df[df['Weather'] == 'Sunny']
print(sunny_days)

   Day  Cups_Sold Weather
0  Mon         10   Sunny
1  Tue         12   Sunny
4  Fri         20   Sunny

# Object-Oriented Programming (OOP) in Python (Classes and Objects)
It shows how to create a "blueprint" (the Class) and then create a specific "instance" (the Object) from that blueprint.

In [ ]:
class Disease:
  def __init__(self, disease = 'Depression'):
    self.type = disease

  def getName(self):
    print("Mental Health Diseases: {0}".format(self.type))

d1 = Disease('Social Anxiety Disorder')
d1.getName()

Mental Health Diseases: Social Anxiety Disorder

# Exception Handling in Python

In [ ]:
# Try Catch Block
# The try block will generate a NameError, because y is not defined:

try:
  print(y)
except NameError:
  print("Well, the variable y is not defined")
except:
  print("OMG, Something else went wrong")

Well, the variable y is not defined

In [ ]:

try:
 Value = int(input("Type a number between 1 and 10:"))
except ValueError:
  print("You must type a number between 1 and 10!")
else:
  if (Value > 0) and (Value <= 10):
      print("You typed: ", Value)
  else:
      print("The value you typed is incorrect!")

Type a number between 1 and 10:66
The value you typed is incorrect!

# Numpy Array Basics

In [5]:
# importing numpy
import numpy as np

# Defining 1D array
my1DArray = np.array([1, 8, 27, 64])
print("1DArray")
print(my1DArray)

# Defining and printing 2D array
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print("2DArray")
print(my2DArray)

#Defining and printing 3D array
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]])
print("3DArray")
print(my3Darray)

1DArray
[ 1  8 27 64]
2DArray
[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
3DArray
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]

**Metadata**—information about the data itself. While the numbers inside the array are important, these commands tell you how the computer "sees" and "organizes" those numbers in its memory.

In [ ]:
# Print out memory address
print(my2DArray.data)

# Print the shape of array
print(my2DArray.shape)

# Print out the data type of the array
print(my2DArray.dtype)

"""
Print the stride of the array.

So what is stride of array?  It is the number of locations in memory between
beginnings of successive array elements, measured in bytes or in units of the
size of the array's elements
"""
print(my2DArray.strides)

<memory at 0x7e9bd04f1f20>
(3, 4)
int64
(32, 8)

# Array using numpy built-in functions

In [ ]:
import numpy as np

# Array of ones
ones = np.ones((3,4))
print(ones)

# Array of zeros
zeros = np.zeros((2,3,4), dtype=np.int16)
print("Array with zeros")
print(zeros)

# Array with random values
print("Random array")
print(np.random.random((2,2)))

# Empty array
emptyArray = np.empty((3,2))
print("Empty Array")
print(emptyArray)

# Full array
fullArray = np.full((2,2), 7)
print("Full Array")
print(fullArray)


# Array of evenly-spaced values
evenSpacedArray = np.arange(10, 25, 5)
print("Array of Evenly-Spaced Values (arange)")
print(evenSpacedArray)

# Array of evenly-spaced values
evenSpacedArray2 = np.linspace(0, 2, 9)
print("Array of Evenly-Spaced Values (linspace)")
print(evenSpacedArray2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with zeros
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Random array
[[0.93883176 0.65754214]
 [0.79562484 0.71064557]]
Empty Array
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Full Array
[[7 7]
 [7 7]]
Fill Array
[[7 7]
 [7 7]]
Array of Evenly-Spaced Values (arange)
[10 15 20]
Array of Evenly-Spaced Values (linspace)
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

# Numpy array and file operations

In [ ]:
# Save a numpy array into file
x = np.arange(0.0,50.0,1.0)
np.savetxt('data.out', x, delimiter=',')

# Loading numpy array from text
z = np.loadtxt('data.out', unpack=True)
print(z)

# Loading numpy array using genfromtxt method
my_array2 = np.genfromtxt('data.out',
                      skip_header=1,
                      filling_values=-999)
print(my_array2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]

In [ ]:
# Create a file with multiple columns of data
data_multi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.savetxt('multi_column.txt', data_multi, delimiter=',')

# Load the file without unpacking
multi_column = np.loadtxt('multi_column.txt', delimiter=',')
print("Without unpacking:")
print(multi_column)

# Load the file with unpacking
multi_column_unpacked = np.loadtxt('multi_column.txt', delimiter=',', unpack=True)
print("With unpacking:")
print(multi_column_unpacked)

Without unpacking:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
With unpacking:
[[ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]
 [ 3.  6.  9. 12.]]

In [ ]:
# Create a file with missing values (some cells are empty)
data_with_missing = np.array([[1, 2, 3], [4, 5, np.nan], [7, 8, 9], [10, np.nan, 12]])
np.savetxt('missing_data.txt', data_with_missing, delimiter=',', fmt='%f')

# Load the file with unpacking, handling missing values (filling with -999)
missing_data_unpacked = np.genfromtxt('missing_data.txt', delimiter=',', unpack=True, filling_values=-999)
print("With missing data unpacked:")
print(missing_data_unpacked)

With missing data unpacked:
[[ 1.  4.  7. 10.]
 [ 2.  5.  8. nan]
 [ 3. nan  9. 12.]]

# Inspecting numpy arrays

In [ ]:
# Print the number of `my2DArray`'s dimensions
print(my2DArray.ndim)

# Print the number of `my2DArray`'s elements
print(my2DArray.size)

# Print information about `my2DArray`'s memory layout
print(my2DArray.flags)

# Print the length of one array element in bytes
print(my2DArray.itemsize)

# Print the total consumed bytes by `my2DArray`'s elements
print(my2DArray.nbytes)

2
12
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
8
96

# Broadcasting in NumPy
Broadcasting is a mechanism that permits `NumPy` to operate with arrays of different shapes when performing arithmetic operations.

In [ ]:
# Rule 1: Two dimensions are operatable if they are equal
# Create an array of two dimension
A =np.ones((6, 8))

# Shape of A
print(A.shape)

# Create another array
B = np.random.random((6,8))

# Shape of B
print(B.shape)

# Sum of A and B, here the shape of both the matrix is same.
print(A + B)

(6, 8)
(6, 8)
[[1.64613513 1.81218169 1.73277236 1.57617341 1.82402347 1.74772911
  1.22843733 1.3993954 ]
 [1.4660033  1.33101593 1.14628103 1.15712902 1.66748722 1.37379544
  1.62748161 1.7947295 ]
 [1.52599628 1.16567587 1.29470105 1.88796265 1.17581034 1.28402744
  1.83282509 1.723289  ]
 [1.53980657 1.5358293  1.7890984  1.60113655 1.1386734  1.66052094
  1.90500048 1.69306468]
 [1.81646704 1.30210421 1.59608074 1.87246912 1.57628331 1.68802283
  1.24708731 1.43667052]
 [1.28634605 1.80769536 1.36572846 1.67252402 1.37322953 1.55805199
  1.31193578 1.24668215]]

In [ ]:
# Rule 2: Two dimensions are also comptable when one of them is 1
# Initialize `x`
x = np.ones((3,4))
print(x)

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.arange(4)
print(y)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x - y

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[0 1 2 3]
(4,)

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [ ]:
# Rule 3: Arrays can be broadcasted together if they are compatible in all dimensions

x = np.zeros((3,4))
y = np.ones((5, 1, 4))
print(x + y)

# Analytical question
"""
The dimensions of x(6,8) and y(10,1,8) are diffrent. However, it is possible
to add them. Why is that? Also, change y(10,2,8) or y(10,1,4) it will
give ValueError. Can you find out why?
"""

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

'\nThe dimensions of x(6,8) and y(10,1,8) are diffrent. However, it is possible \nto add them. Why is that? Also, change y(10,2,8) or y(10,1,4) it will \ngive ValueError. Can you find out why?\n'

# Numpy and mathematics at work

In [ ]:
# Basica operations (+, -, *, /, %)
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 4, 9], [2, 3, -2]])

# Add two array
add = np.add(x, y)
print(add)

# Subtract two array
sub = np.subtract(x, y)
print(sub)

# Multipley two array
mul = np.multiply(x, y)
print(mul)

# Divide x, y
div = np.divide(x,y)
print(div)

# Calculated the remainder of x and y
rem = np.remainder(x, y)
print(rem)

[[ 2  6 12]
 [ 4  6  2]]
[[ 0 -2 -6]
 [ 0  0  6]]
[[ 1  8 27]
 [ 4  9 -8]]
[[ 1.          0.5         0.33333333]
 [ 1.          1.         -2.        ]]
[[0 2 3]
 [0 0 0]]

# Subset, Slice, And Index Arrays

In [ ]:
x = np.array([10, 20, 30, 40, 50])

# Select items at index 0 and 1
print(x[0:2])

# Select item at row 0 and 1 and column 1 from 2D array
y = np.array([[ 1,  2,  3,  4], [ 9, 10, 11 ,12]])
print(y[0:2, 1])

# Specifying conditions
biggerThan2 = (y >= 2)
print(y[biggerThan2])

[10 20]
[ 2 10]
[ 2  3  4  9 10 11 12]

In [ ]:
# Importing pandas
import pandas as pd

# Can you set default parameters in Pandas?

In [ ]:
print("Pandas Version:", pd.__version__)

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

Pandas Version: 0.24.2

# Data strcutre of pandas


*   Series
*   DataFrames

In [ ]:
series = pd.Series([2, 3, 7, 11, 13, 17, 19, 23])
print(series)

# Creating dataframe from Dictionary
dict_df = [{'A': 'Apple', 'B': 'Ball'},{'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}]
dict_df = pd.DataFrame(dict_df)
print(dict_df)

# Creating dataframe from Series
series_df = pd.DataFrame({
    'A': range(1, 5),
    'B': pd.Timestamp('20190526'),
    'C': pd.Series(5, index=list(range(4)), dtype='float64'),
    'D': np.array([3] * 4, dtype='int64'),
    'E': pd.Categorical(["Depression", "Social Anxiety", "Bipolar Disorder", "Eating Disorder"]),
    'F': 'Mental health',
    'G': 'is challenging'
})
print(series_df)

# Creating a dataframe from ndarrays
sdf = {
    'County':['Østfold', 'Hordaland', 'Oslo', 'Hedmark', 'Oppland', 'Buskerud'],
    'ISO-Code':[1,2,3,4,5,6],
    'Area': [4180.69, 4917.94, 454.07, 27397.76, 25192.10, 14910.94],
    'Administrative centre': ["Sarpsborg", "Oslo", "City of Oslo", "Hamar", "Lillehammer", "Drammen"]
    }
sdf = pd.DataFrame(sdf)
print(sdf)

0     2
1     3
2     7
3    11
4    13
5    17
6    19
7    23
dtype: int64
           A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat
   A          B    C  D                 E              F               G
0  1 2019-05-26  5.0  3        Depression  Mental health  is challenging
1  2 2019-05-26  5.0  3    Social Anxiety  Mental health  is challenging
2  3 2019-05-26  5.0  3  Bipolar Disorder  Mental health  is challenging
3  4 2019-05-26  5.0  3   Eating Disorder  Mental health  is challenging
      County  ISO-Code      Area Administrative centre
0    Østfold         1   4180.69             Sarpsborg
1  Hordaland         2   4917.94                  Oslo
2       Oslo         3    454.07          City of Oslo
3    Hedmark         4  27397.76                 Hamar
4    Oppland         5  25192.10           Lillehammer
5   Buskerud         6  14910.94               Drammen

# Loading a dataset into Pandas DataFrame

In [ ]:
import pandas as pd
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender','capital_gain','capital_loss','hours_per_week','country_of_origin','income']
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns)
df.head(10)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,ethnicity,gender,capital_gain,capital_loss,hours_per_week,country_of_origin,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [ ]:
# Displays the rows, columns, data types and memory used by the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age                  32561 non-null int64
workclass            32561 non-null object
fnlwgt               32561 non-null int64
education            32561 non-null object
education_num        32561 non-null int64
marital_status       32561 non-null object
occupation           32561 non-null object
relationship         32561 non-null object
ethnicity            32561 non-null object
gender               32561 non-null object
capital_gain         32561 non-null int64
capital_loss         32561 non-null int64
hours_per_week       32561 non-null int64
country_of_origin    32561 non-null object
income               32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
# Displays the no of data points and columns in the dataframe
df.shape

(32561, 15)

In [ ]:
# Display all columns of the dataframe
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
       'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
       'income'],
      dtype='object')

In [ ]:
# Displays summary statistics for each numerical column in the dataframe
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

# Selecting rows and columns in the dataframe

In [ ]:
# Selects a row
df.iloc[10]

# Selects 10 rows
df.iloc[0:10]

# Selects a range of rows
df.iloc[10:15]

 # Selects the last 2 rows
df.iloc[-2:]

# Selects every other row in columns 3-5
df.iloc[::2, 3:5].head()

    education  education_num
0   Bachelors             13
2     HS-grad              9
4   Bachelors             13
6         9th              5
8     Masters             14

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(24)
df = pd.DataFrame({'F': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 5), columns=list('EDCBA'))],
               axis=1)
df.iloc[0, 2] = np.nan
df

      F         E         D         C         B         A
0   1.0  1.329212       NaN -0.316280 -0.990810 -1.070816
1   2.0 -1.438713  0.564417  0.295722 -1.626404  0.219565
2   3.0  0.678805  1.889273  0.961538  0.104011 -0.481165
3   4.0  0.850229  1.453425  1.057737  0.165562  0.515018
4   5.0 -1.336936  0.562861  1.392855 -0.063328  0.121668
5   6.0  1.207603 -0.002040  1.627796  0.354493  1.037528
6   7.0 -0.385684  0.519818  1.686583 -1.325963  1.428984
7   8.0 -2.089354 -0.129820  0.631523 -0.586538  0.290720
8   9.0  1.264103  0.290035 -1.970288  0.803906  1.030550
9  10.0  0.118098 -0.021853  0.046841 -1.628753 -0.392361

In [ ]:
# Define a function that should color the values that are less than 0
def colorNegativeValueToRed(value):
  if value < 0:
    color = 'red'
  elif value > 0:
    color = 'black'
  else:
    color = 'green'

  return 'color: %s' % color

In [ ]:
s = df.style.applymap(colorNegativeValueToRed, subset=['A','B','C','D','E'])
s

In [ ]:
# Let us hightlight max value in the column with green background and min value with orange background
def highlightMax(s):
    isMax = s == s.max()
    return ['background-color: orange' if v else '' for v in isMax]

def highlightMin(s):
    isMin = s == s.min()
    return ['background-color: green' if v else '' for v in isMin]

In [ ]:
df.style.apply(highlightMax).apply(highlightMin).highlight_null(null_color='red')

In [ ]:
import seaborn as sns

cm = sns.light_palette("pink", as_cmap=True)

s = df.style.background_gradient(cmap=cm)
s

/usr/local/lib/python3.6/dist-packages/matplotlib/colors.py:512: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

In [ ]:
class Disease:
  def __init__(self, disease = 'Depression'):
    self.type = disease

  def getName(self):
    print("Mental Health Diseases: {0}".format(self.type))

d1 = Disease('Social Anxiety Disorder')
d1.getName()

Mental Health Diseases: Social Anxiety Disorder

In [ ]:
try:
  Value = int(input("Type a number between 1 and 10:"))
except ValueError:
   print("You must type a number between 1 and 10!")
else:
   if (Value > 0) and (Value <= 10):
       print("You typed: ", Value)
   else:
       print("The value you typed is incorrect!")

Type a number between 1 and 10:333
The value you typed is incorrect!